### ISSUE TITLE
K-9 mail compatibility:  NOT and OR clauses implementation needed

### ISSUE THREAD

**Issue by iot-resister** [emersion/hydroxide#96] opened 2020-05-04 16:10 UTC
I got K-9 mail working by commenting out the following conditional.

https://github.com/emersion/hydroxide/blob/master/imap/mailbox.go#L310

**Comment by emersion** [comment] 2021-02-24 08:58
Duplicate of https://github.com/emersion/hydroxide/issues/149

**Closed by emersion** 2021-02-24 08:58 UTC
