### ISSUE TITLE
SMTP authenticate error using Laravel

### ISSUE THREAD

**Issue by Mr-Sheep** [emersion/hydroxide#90] opened 2020-04-05 17:21 UTC
Hi,
I been trying to deploy hydroxide on my server, but encountered this error when sending emails using Laravel:
```
Failed to authenticate on SMTP server with username "my Protonmail Username" using 1 possible authenticators. Authenticator CRAM-MD5 returned Expected response code 235 but got code "535", with message "535 5.7.0 authentication failed
".
```
FYI, I used PM2 as daemon with command `pm2 start hydroxide -- smtp`
Any suggestions?

**Comment by emersion** [comment] 2020-04-05 21:01
CRAM-MD5 is legacy and should not be used. Plain-text auth with TLS should be used instead.

Duplicate of https://github.com/emersion/hydroxide/issues/13

**Closed by emersion** 2020-04-05 21:01 UTC

**Comment by Mr-Sheep** [comment] 2020-04-06 07:28
So rather than using none for security as mentioned in https://github.com/emersion/hydroxide#smtp . I should use tls for my security setting?

**Comment by emersion** [comment] 2020-04-06 07:29
You can use none + plain-text if you aren't running the client on a different machine. For TLS, see #13.

**Comment by Mr-Sheep** [comment] 2020-04-06 07:58
Thanks for help. I'll look it up
In the mean time,  I wonder if there's anything wrong with my laravel config
```
MAIL_DRIVER=smtp
MAIL_HOST=localhost
MAIL_PORT=1025
MAIL_USERNAME=username
MAIL_PASSWORD=bridge password
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=username@example.com
MAIL_FROM_NAME=username
```
