### ISSUE TITLE
Invalid input error

### ISSUE THREAD

**Issue by inkskull** [emersion/hydroxide#74] opened 2019-11-03 22:21 UTC
Hi,

I've installed hydroxide with the fix for the recent protonmail api modification. I'm able to launch the server and get the password despite the "failed to check SRP modulus signature warning". But each time i'm triyng to login to the imap server hydroxide print's this error message : 

`2019/11/03 21:56:57 request failed: POST https://mail.protonmail.com/api/auth/refresh: [2000] Invalid input
`

I've tried to login to the server with netcat and python's imaplib and I get the same error.

Here is what I get with netcat : 

```
nc 127.0.0.1 1143
* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR AUTH=PLAIN] IMAP4rev1 Service Ready
001 LOGIN username 0/j+JrsrqeznBiSzdDZFyImmzyvnj1aCE1ulTs9lEds= 
001 NO [2000] Invalid input

```

The username and the password are ok when i'm triyng with a false username or password I'm getting this answer : 

`001 NO Invalid username or password`

Thanks for your help.

**Comment by emersion** [comment] 2019-11-04 00:01
Duplicate of https://github.com/emersion/hydroxide/issues/70

**Closed by emersion** 2019-11-04 00:01 UTC
