### ISSUE TITLE
openpgp: incorrect key

### ISSUE THREAD

**Issue by sbinet** [emersion/hydroxide#103] opened 2020-06-30 14:45 UTC
hi there,

I am trying to read emails w/ [aerc](https://aerc-mail.org/).
I am using protonmail and hydroxide as a bridge to proton.

whenever I try to display an email w/ aerc (but also with Alpine, FWIW), I get:

```
>> GET /api/messages/<some-token>
<< GET /api/messages/<some-token>
&struct { protonmail.resp; Message *protonmail.Message }{resp:protonmail.resp{Code:1000, RawAPIError:(*protonmail.RawAPIError)(nil)}, Message:(*protonmail.Message)(0xc000174780)}
--- packet: *packet.EncryptedKey
### default: 0x12 18
--- packet: *packet.SymmetricallyEncrypted
found 0 sym-keys
found 0 pub-keys
found se: &packet.SymmetricallyEncrypted{MDC:true, contents:(*packet.spanReader)(0xc00025c8e0), prefix:[]uint8(nil)}
>>>> error1
2fSUhg NO openpgp: incorrect key
YbVObw UID FETCH 48 (BODYSTRUCTURE ENVELOPE INTERNALDATE FLAGS UID BODY.PEEK[HEADER])
* 48 FETCH (BODYSTRUCTURE (("text" "html" () NIL NIL "quoted-printable" 0 0 NIL ("inline" ()) NIL NIL) "mixed" NIL NIL NIL NIL) ENVELOPE ("Tue, 30 Jun 2020 15:04:58 +0200" "Re: [gonum/gonum] mat: clarify docs for Dense.Solve and VecDense.SolveVec (#1368)" (("=?utf-8?q?Vladim=C3=ADr_Chalupeck=C3=BD?=" NIL "notifications" "github.com")) () () (("gonum/gonum" NIL "gonum" "noreply.github.com")) (("Subscribed" NIL "subscribed" "noreply.github.com")) () "" "gonum/gonum/pull/1368/issue_event/3497648546@github.com") INTERNALDATE "30-Jun-2020 15:04:58 +0200" FLAGS (\Seen x-gonum) UID 48 BODY[HEADER] {480}
Content-Type: multipart/mixed;
 boundary=ca81eba5d8f3c773c25507ba3ceae18c700e8d42b127fbf351e51d116ef9
Message-Id: gonum/gonum/pull/1368/issue_event/3497648546@github.com
Cc: "Subscribed" <subscribed@noreply.github.com>
To: "gonum/gonum" <gonum@noreply.github.com>
From: =?utf-8?q?Vladim=C3=ADr_Chalupeck=C3=BD?= <notifications@github.com>
Subject: Re: [gonum/gonum] mat: clarify docs for Dense.Solve and
 VecDense.SolveVec (#1368)
Date: Tue, 30 Jun 2020 15:04:58 +0200

)
YbVObw OK UID FETCH completed

```

and the body of the email is not rendered/displayed.

I've tried to `git grep` a bit in `hydroxide` source tree to see where this `openpgp: %v` string could come from, to no avail.
I guess it's coming from `x/crypto/openpgp/errors.keyIncorrectError` or `ErrKeyIncorrect`.
and it's coming from:
https://github.com/golang/crypto/blob/7ac97ebec9cb7ab8b44b571f6ec4cee333dc4309/openpgp/read.go#L185

here is the diff if one wants to follow along:
```diff
diff --git a/openpgp/read.go b/openpgp/read.go
index 6ec664f..f2e236f 100644
--- a/openpgp/read.go
+++ b/openpgp/read.go
@@ -10,6 +10,7 @@ import (
 	_ "crypto/sha256"
 	"hash"
 	"io"
+	"log"
 	"strconv"
 
 	"golang.org/x/crypto/openpgp/armor"
@@ -104,6 +105,7 @@ ParsePackets:
 		if err != nil {
 			return nil, err
 		}
+		log.Printf("--- packet: %T", p)
 		switch p := p.(type) {
 		case *packet.SymmetricKeyEncrypted:
 			// This packet contains the decryption key encrypted with a passphrase.
@@ -113,17 +115,27 @@ ParsePackets:
 			// This packet contains the decryption key encrypted to a public key.
 			md.EncryptedToKeyIds = append(md.EncryptedToKeyIds, p.KeyId)
 			switch p.Algo {
-			case packet.PubKeyAlgoRSA, packet.PubKeyAlgoRSAEncryptOnly, packet.PubKeyAlgoElGamal:
+			case packet.PubKeyAlgoRSA:
+				log.Printf("### AlgoRSA")
+				break
+			case packet.PubKeyAlgoRSAEncryptOnly:
+				log.Printf("### AlgoRSAEncOnly")
+				break
+			case packet.PubKeyAlgoElGamal:
+				log.Printf("### AlgoRSAElGamal")
 				break
 			default:
+				log.Printf("### default: %#v %d", p.Algo, p.Algo)
 				continue
 			}
 			var keys []Key
+			log.Printf("keyid=%v", p.KeyId)
 			if p.KeyId == 0 {
 				keys = keyring.DecryptionKeys()
 			} else {
 				keys = keyring.KeysById(p.KeyId)
 			}
+			log.Printf("keys: %d", len(keys))
 			for _, k := range keys {
 				pubKeys = append(pubKeys, keyEnvelopePair{k, p})
 			}
@@ -152,10 +164,16 @@ FindKey:
 		candidates = candidates[:0]
 		candidateFingerprints := make(map[string]bool)
 
-		for _, pk := range pubKeys {
+		log.Printf("found %d sym-keys", len(symKeys))
+		log.Printf("found %d pub-keys", len(pubKeys))
+		log.Printf("found se: %#v", se)
+		for ii, pk := range pubKeys {
+			log.Printf("--- pub=key[%d]: %#v", ii, pk)
 			if pk.key.PrivateKey == nil {
+				log.Printf("--> nil private-key")
 				continue
 			}
+			log.Printf("--> encrypted=%v", pk.key.PrivateKey.Encrypted)
 			if !pk.key.PrivateKey.Encrypted {
 				if len(pk.encryptedKey.Key) == 0 {
 					pk.encryptedKey.Decrypt(pk.key.PrivateKey, config)
@@ -182,10 +200,12 @@ FindKey:
 		}
 
 		if len(candidates) == 0 && len(symKeys) == 0 {
+			log.Printf(">>>> error1")
 			return nil, errors.ErrKeyIncorrect
 		}
 
 		if prompt == nil {
+			log.Printf(">>>> error2")
 			return nil, errors.ErrKeyIncorrect
 		}
 
```

is this related to https://github.com/emersion/hydroxide/issues/46 ?
(I see the `p.Algo` from https://github.com/golang/crypto/blob/7ac97ebec9cb7ab8b44b571f6ec4cee333dc4309/openpgp/read.go#L115 is, in my case `openpgp/packet.PubKeyAlgoECDH (==18)`)

**Comment by emersion** [comment] 2020-06-30 14:50
Ah, I guess we don't manage to load your ECDH key, so we just provide no key to openpgp?

Would be nice to add a sanity check to make sure we always have at least one key when decrypting a message, and fail early with a better error message otherwise.

>is this related to #46 ?

Yeah, sounds like the root cause is the same. Does https://github.com/emersion/hydroxide/pull/102 help?

**Comment by sbinet** [comment] 2020-06-30 14:52
yes, #102 does help.
with it, I can see my emails :)

**Comment by emersion** [comment] 2020-07-02 10:24
Fixed in https://github.com/emersion/hydroxide/pull/102

**Closed by emersion** 2020-07-02 10:24 UTC

**Comment by arnottcr** [comment] 2022-04-06 14:36
The code is failing for me [here](https://github.com/emersion/hydroxide/blob/3c5283705389a690e1631dbe771aef4b31702109/protonmail/contacts.go#L194) because we are missing a key. I can confirm that all the "Email encryption keys" are being fetched and exist in the `openpgp.KeyRing`, including duplicates. While the first of the "Contact encryption keys" is shared with an email encryption key, thus is in the key ring, there is a second, default key that is not shared with email and is missing from the keyring.

I will dig into how to fetch these keys specifically, but it looks like they are already in memory, since they would have been fetched as part of https://old.protonmail.com/api/users. I guess we do not merge the two keyrings? Should be pretty easy?
