### ISSUE TITLE
Multiple warnings on auth

### ISSUE THREAD

**Issue by grantyn** [emersion/hydroxide#99] opened 2020-06-15 21:17 UTC
Installed package as shown in instructions after installing go.

When I run hydroxide auth <my-username> and enter my password the app returns the following warnings:

2020/06/15 15:14:38 warning: failed to check SRP modulus signature: openpgp: unsupported feature: public key algorithm 22
2020/06/15 15:14:39 warning: failed to read key "grant.nakamura@wfphc.com": failed to read private key: openpgp: unsupported feature: public key type: 22
2020/06/15 15:14:40 warning: failed to read key "manager@wfphc.com": failed to read private key: openpgp: unsupported feature: public key type: 22
2020/06/15 15:14:40 warning: failed to read key "doug.pitman@protonmail.com": failed to read private key: openpgp: unsupported feature: public key type: 22

I'm unable to use the bridge via my client. Any help would be appreciated.

**Comment by emersion** [comment] 2020-06-15 21:18
Duplicate of https://github.com/emersion/hydroxide/issues/46

**Closed by emersion** 2020-06-15 21:18 UTC
