### ISSUE TITLE
Trying to install on OpenBSD

### ISSUE THREAD

**Issue by pau-amaro-seoane** [emersion/hydroxide#107] opened 2020-07-07 19:01 UTC
Hi, thanks for this. I am trying to install this on OpenBSD -current:

```
$ go version
go version go1.13.9 openbsd/amd64
```
However, I am facing this problem. I have zero experience with go, so please be patient with me... When I try to install it, I get (as user)
```

go: finding github.com/emersion/hydroxide v0.2.15
go: downloading github.com/emersion/hydroxide v0.2.15
go: extracting github.com/emersion/hydroxide v0.2.15
go: downloading golang.org/x/crypto v0.0.0-20200221231518-2aa609cf4a9d
go: extracting golang.org/x/crypto v0.0.0-20200221231518-2aa609cf4a9d
go: finding golang.org/x/crypto v0.0.0-20200221231518-2aa609cf4a9d
# github.com/emersion/hydroxide/protonmail
/home/pau/go/pkg/mod/github.com/emersion/hydroxide@v0.2.15/protonmail/contacts.go:167:66: too many arguments in call to openpgp.CheckArmoredDetachedSignature
        have (openpgp.KeyRing, *bytes.Buffer, io.Reader, nil)
        want (openpgp.KeyRing, io.Reader, io.Reader)
/home/pau/go/pkg/mod/github.com/emersion/hydroxide@v0.2.15/protonmail/contacts.go:193:55: too many arguments in call to openpgp.CheckArmoredDetachedSignature
        have (openpgp.KeyRing, *strings.Reader, *strings.Reader, nil)
        want (openpgp.KeyRing, io.Reader, io.Reader)
/home/pau/go/pkg/mod/github.com/emersion/hydroxide@v0.2.15/protonmail/crypto.go:39:21: subkey.PublicKey.KeyExpired undefined (type *packet.PublicKey has no field or method KeyExpired)
/home/pau/go/pkg/mod/github.com/emersion/hydroxide@v0.2.15/protonmail/crypto.go:56:137: i.SelfSignature.SigExpired undefined (type *packet.Signature has no field or method SigExpired)
/home/pau/go/pkg/mod/github.com/emersion/hydroxide@v0.2.15/protonmail/crypto.go:73:21: subkey.PublicKey.KeyExpired undefined (type *packet.PublicKey has no field or method KeyExpired)
/home/pau/go/pkg/mod/github.com/emersion/hydroxide@v0.2.15/protonmail/crypto.go:87:80: i.SelfSignature.SigExpired undefined (type *packet.Signature has no field or method SigExpired)
/home/pau/go/pkg/mod/github.com/emersion/hydroxide@v0.2.15/protonmail/srp.go:45:41: too many arguments in call to openpgp.CheckDetachedSignature
        have (openpgp.EntityList, *bytes.Reader, io.Reader, nil)
        want (openpgp.KeyRing, io.Reader, io.Reader)

```

As root, I am getting the same error message... any idea? This is OpenBSD current 6.7 GENERIC.MP#323 amd64

**Comment by emersion** [comment] 2020-07-07 19:02
Duplicate of https://github.com/emersion/hydroxide/issues/106

**Closed by emersion** 2020-07-07 19:02 UTC

**Comment by pau-amaro-seoane** [comment] 2020-07-07 19:06
thanks and apologies - I should've checked. It is working.
