### ISSUE TITLE
Doesn't work with Kube due to missing features.

### ISSUE THREAD

**Issue by vesim987** [emersion/hydroxide#134] opened 2020-12-14 01:56 UTC
Hi,

[Kube](https://kube-project.com/) is complaining about a couple of missing features:
```
Warning: {yyy}.imapresource                       : Continuing after protocol error:  "xxx" Error:  Error:  7 Msg:  "Search failed, server replied: A000006 NO search queries with NOT or OR clauses are not yet implemented .\n Sent command: UID SEARCHSINCE \"30-Nov-2020\" NOT DELETED"
[...]
Warning: {yyy}.imapserverproxy                    : Server doesn't support required capability:  "UIDPLUS"
Warning: {yyy}.imapserverproxy                    : Server doesn't support required capability:  "NAMESPACE"
Warning: {yyy}.imapserverproxy                    : Job failed:  "Namespace failed, server replied: A000004 BAD Unknown command .\n Sent command: NAMESPACE" KIMAP2::NamespaceJob 102
```

**Comment by emersion** [comment] 2021-02-24 08:57
Actually it's a duplicate of https://github.com/emersion/hydroxide/issues/149

**Closed by emersion** 2021-02-24 08:57 UTC
